# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  lane :toPgy do
    puts("开始打包Android APK!");
    gradle(task: "clean assembleRelease")
    puts("------打包后App信息：------")
  
 
    #上传到蒲公英
    pgyer(api_key: "982c1db15da6f537091af87ea1a5b3d6", apk: "../build/app/outputs/apk/release/app-release.apk")
  end
  lane :uploadToPgy do
    puts("开始上传蒲公英!");
    #上传到蒲公英
    pgyer(api_key: "982c1db15da6f537091af87ea1a5b3d6", apk: "../build/app/outputs/apk/release/app-release.apk")
  end
end
